### ISSUE TITLE
Removing Bad/Null example illustration in Tidy Data

### ISSUE THREAD

**Issue by LWhit528** [LibraryCarpentry/lc-spreadsheets#124]
https://librarycarpentry.org/lc-spreadsheets/02-common-mistakes/index.html#null

The example used in the Tidy Data common mistakes for null values is unclear. Does a user write "blank" or leave the cell blank?
Perhaps there is a better illustration that can be used?

**Comment by morskyjezek** [comment]
Hi @LWhit528 - thanks for this contribution! I see what you mean about the examples offered for null values. They are mostly explained in the image, which also presents an accessibility issue. 

My understanding of this is that the cited source suggests that the cell with no value is left blank (no spaces or other characters), but we should also note that there are other ways to approach the no value issue. In fact, the point is that the data is consistent throughout and uses only one option for noting a no value. A blank cell may be understood in some fields as no value, but it does have some ambiguity. Since there is some question about what recommendation is actually being made, though, I wonder if there are any other maintainers who would like to chime in? Tagging @jt14den and @shlake 

To address this, I would propose adding some explanatory text prior to the "Example" and "Solution" paragraphs similar to what I wrote above. I would also propose that we make these recommendations in a table (similar to the illustration of "Field name problems") rather than an image, so that it is possible to search, use a screenreader, and copy the suggestions. Any thoughts?

**Comment by morskyjezek** [comment]
Thanks @SandiCal ! That's a great suggestion. Your suggested text offers a clearer way to express the issue and main points that we want to get across here. I like the way you've pointed out that null vals are important since they separate no value from missing data. 👍🏼  

I agree about removing the image (the table is currently in an image), but I wonder if an abbreviated table that covers a few of the more useful approaches in the platforms we use/mention in Library Carpentry (Python, R, spreadsheet apps) might be helpful. I'll see how it looks. 

I will start working on a proposed change based on this suggested language. Hopefully we can get this resolved in a timely way over the next month or so.

**Comment by SandiCal** [comment]
I did a little research to see if I could find another table from an alternative source on best practices for null values, and I was surprised at how little I found. I think it would be great if Carpentries put something out there. I'm happy to help if you want a hand.

**Comment by shlake** [comment]
Sorry, not to chime in earlier, but I am confused as to what is being suggested.

The suggested recommendation to leave it blank (leave the cell blank - nothing in it) is not in quotes ("blank"). So I am not sure where you are seeing that RE: comment above - 
`the "blank" recommendation is ambiguous. Since none of the other suggested values are in quotes, it looks as though the authors are recommending use of the word "Blank" to indicate null values.`

**Comment by shlake** [comment]
On another note. The Tidy Data Lesson in Library Carpentry came from the [Data Organization in Spreadsheets for Ecologists](https://datacarpentry.org/spreadsheet-ecology-lesson/) (and were edited for Library Carpentry with different examples that were supposed to be more meaningful to Librarians - by the original maintainers - which I was not one of).

Those lessons have been updated and here is how the Null/blank/missing data has been edited, so maybe that's a good place to start - I will note they still have the image from the paper and not a real chart:

https://datacarpentry.org/spreadsheet-ecology-lesson/02-common-mistakes/index.html#zeros

**Comment by morskyjezek** [comment]
I think the confusion is coming from the table included in the illustration. There, the word Blank appears in the Null values column, which makes it seem to recommend to write the word Blank in the cell. The text does not suggest this, the image seems to cause the confusion.

**Comment by shlake** [comment]
I found the same chart in text format: https://instr.iastate.libguides.com/spreadsheets/zero

Maybe use this text version and be edit it to be clear on what "Blank" means?

**Comment by kenlacey** [comment]
I have found the examples confusing as there is no definite outcome from the table.
This is one of those points where I add “How you record Null values needs to be documented in your data design”
It may also be added to the tab where you “keep track of the steps you took in your clean up or analysis.”

Take care
Ken Lacey

[turn on images]<https://www.tudublin.ie/>
Ken Lacey
Library Digital Developer
Technological University Dublin
________________________________________
–  01 220 5119  – tudublin.ie<https://tudublin.ie/>

Teach na Páirce Ghráinseach Ghormáin, D07 EWV4, Éire
Park House Grangegorman, D07 EWV4, Ireland

**Comment by tobyhodges** [comment]
Thanks everyone for the thoughtful discussion here. Today I opened issues on the repositories for the two Data Carpentry data organisation lessons that include this table, suggesting that the screenshots be replaced with HTML tables to improve the accessibility. I'm linking cross-linking between this issue and those, in the hope that someone who wants to fix it in one location will also apply their solution to the other two lessons.

https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/319
https://github.com/datacarpentry/spreadsheets-socialsci/issues/151

**Comment by hoytpr** [comment]
@tobyhodges Here the the table as HTML. Hope this helps

[null_values_table.txt](https://github.com/LibraryCarpentry/lc-spreadsheets/files/10126754/null_values_table.txt)

**Comment by morskyjezek** [comment]
Changes have been drafted and proposed in PR #132 . This appears to be a relatively uncontroversial change and will align the lesson with the changes made in the Data Carpentry lessons. Barring any further comments, I will merge the PR and close this issue as resolved after 24 hours.
