### ISSUE TITLE
In setup: CSV option to open for non-Microsoft?

### ISSUE THREAD

**Issue by jas58** [LibraryCarpentry/lc-spreadsheets#148]
### How could the content be improved?

I didn't see an issue discussing this already, so ignore if it's been hashed out elsewhere.
I use LibreOffice (no money to buy Microsoft) so wonder why the lesson's file to open is only an .xslx option.  Is there no room to add a link to the .csv version of the file?  Or is it normal practice to expect the minority of users can make do on their own working through forcing Libre to open the .xlsx file?

### Which part of the content does your suggestion apply to?

setup (file to download and open)

**Comment by morskyjezek** [comment]
Hi @jas58 - I'm a current maintainer but wasn't involved in the original creation of this lesson. As far as I can tell, the lesson was designed around Excel (as you noted there are many points where Excel is either directly mentioned or assumed). I've tried to move away from this in some parts, such as the tables that provide similar commands in different programs including open versions. 

I don't know if the suggestion you've made - of offering a CSV version - has been considered in the past, but I appreciate the suggestion of making available an open version of the sample data. Given the current data, which has multiple sheets in the sample file, it would be difficult to make this available as a CSV. But maybe it would be possible to offer an open document format (ODF) as a recognition that not all users are starting with Excel. 

Another possible approach might be instructions in the setup for those using LibreOffice or open office programs about how to open the file. Generally, it seems like this would be of similar complexity to opening a CSV, which usually requires additional calibration steps, too. I would lean toward this second option, but it would be great to hear your thoughts on this.

**Comment by morskyjezek** [comment]
I've been reviewing pull requests and issues on this lesson again. This is a good issue to raise. The suggestion to output in CSV is reiterated in episode 6, so this issue is raised generally. When I reviewed the sample data for the workshop, I remembered that part of the demonstration is multiple tables in one sheet, and also multiple, conflicting sheets. CSVs can include extraneous tables in some cases, but they don't include multiple sheets. Since there are Libre versions of software that can readily open xls (or it can be done in Google Sheets), I don't think it would be useful to provide a CSV sample data file at the beginning of the workshop.

**Comment by jas58** [comment]
I'm thinking of global users,  offline workshops,  and countries that block
Google,  or users for whom Microsoft is prohibitively expensive.  I can
raise this issue with the lesson setup task force next month,  too.

**Comment by morskyjezek** [comment]
I agree it's a good thing to raise, and possibly it's somewhat beyond the scope of this lesson specifically since this is an issue replicated across the other Carpentries lessons that cover this material. As I mentioned, though, 1) the "messy data issues" illustrated in the dataset can be replicated in CSV, and 2) Libre Office and Open Office don't usually have trouble opening xls files. 

I have added throughout some tables and sections that point out where to do things that operate differently in those other platforms for lesson users not working in Excel, so that's a start. But yes, this might be an issue to discuss across lessons with the task force. I will stay tuned :)
