### ISSUE TITLE
ready to publish?

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/lc-spreadsheets#98]
@shlake Is the lesson ready to publish?  If so we can, ask @fmichonneau to queue it for release.

**Comment by shlake** [comment]
I want to look it over one more time. There were lots of issues closed and things "fixed", so I want to make sure I didn't break anything. 

I'll review tomorrow - Tuesday and update this issue.

**Comment by shlake** [comment]
@jt14den All Clear for publishing.

**Comment by ErinBecker** [comment]
@shlake - thanks for letting us know and for all of the work you've done on this lesson! I'll bring this to the Curriculum Team (@fmichonneau @zkamvar and myself) next Tuesday to discuss next steps in getting this published and let you know if we have any questions.

**Comment by jt14den** [comment]
@ErinBecker Thanks! FYI I communicated with @fmichonneau on Slack about publishing this off-cycle. Also, for some background, the LC Governance Committee and Curriculum Advisory Committee at our last meeting agreed to move this lesson to stable status. I've been tasked by that combined groups to shepherd that forward. I'd like to also get it published in conjunction with this transition.

**Comment by ErinBecker** [comment]
Great, thanks for coordinating this @jt14den and @shlake!

I've just done a quick read through for formatting and noticed three things:
1) One exercise that wasn't formatting correctly (fixed with https://github.com/LibraryCarpentry/lc-spreadsheets/pull/102)
2) A few episodes are missing time estimates for exercises. 
3) The last episode (caveats) still has species names from the ecology spreadsheets lesson and should be changed to the dataset used for this lesson. 

Other than those three things, this looks good to go from me! After those fixes are submitted, @fmichonneau will put together the publication files and update this issue. I'd also love to get a blog post out about this! Would one of you (@jt14den @shlake) be willing to coordinate a blog post with @okhan?

**Comment by jt14den** [comment]
Thanks @ErinBecker for reviewing the lesson and the feedback. We'll work on getting those fixed. A blog entry is a great idea! Thanks for suggesting. @shlake are you game? We can work on it in a gdoc.

**Comment by shlake** [comment]
@jt14den - am “out” on vacation this week. Will look over on Monday.

**Comment by ErinBecker** [comment]
Sounds great. Thanks both!

**Comment by fmichonneau** [comment]
I'll be out next week but I'll happily take care of the release once I'm back on or after July 20th.

**Comment by shlake** [comment]
Added #103 per @ErinBecker review (comment in this issue)

**Comment by shlake** [comment]
Added #104

**Comment by shlake** [comment]
OK, All things @ErinBecker noted have been addressed. @jt14den I think this can be closed and the lesson is ready for "prime time"!

**Comment by jt14den** [comment]
Whoo hoo :raised_hands:! Thanks @shlake.  I emailed @okhan about getting a blog together. When @fmichonneau returns from vacation, we can publish. I have a PR in on the LC website to move it to stable status there.

**Comment by fmichonneau** [comment]
The lesson is now published!

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3954067.svg)](https://doi.org/10.5281/zenodo.3954067)

I suggest you update the README to incldue the DOI and update the citation information as you see fit.

Congratulations on all your hard work on this lesson!
